# Generated by Django 5.2.3 on 2025-08-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('offer', models.TextField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
