# Generated by Django 5.2.3 on 2025-09-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='desctription',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
