# Generated by Django 5.2.3 on 2025-09-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectmodel_desctription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='desctription',
            new_name='description',
        ),
    ]
